# Generated by Django 2.2.18 on 2021-05-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLInjectionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_true_code', models.CharField(max_length=2048)),
                ('sql_false_code', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='SQLInjectionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=2048)),
                ('scan_date', models.DateTimeField(auto_now=True)),
                ('sql_injection_code', models.CharField(max_length=2048)),
                ('result', models.BooleanField()),
            ],
        ),
    ]
