# Generated by Django 2.2.18 on 2021-05-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XSSLog',
            new_name='XXELog',
        ),
    ]
